### PR TITLE
Handle circular references without throwing an exception

### LINKED ISSUE #66: Circular references
A simple circular reference will respond with an error, refering to https://github.com/tedeh/jayson/blob/master/lib/utils.js#L295-L299

Could we leverage something like https://github.com/isaacs/json-stringify-safe to send a valid JSON response regardless of circular references in the response?

### PR DESCRIPTION
**Pull request by gillesdemey**
Apologies for the whitespace that has been removed, dirtying the diff.

Fixes #66

### CODE REVIEW

**Comment by gillesdemey** [comment]
Test suite seems to fail on 0.8, looks like a problem with Jenkins from afar.

**Comment by gillesdemey** [comment]
Tests pass on my local machine with v0.8.28

**Comment by tedeh** [comment]
Thanks

**Comment by gillesdemey** [comment]
Can we push a new (minor) version?

**Pull request merged**
