### PR TITLE
added TLS support

### PR DESCRIPTION
**Pull request by bdunlay**
Added TLS-encrypted TCP sockets as a transport layer with example and tests.

### CODE REVIEW

**Comment by bdunlay** [comment]
If you have an idea of why this is failing on earlier versions of node please let me know. Code is almost identical to TCP code but seems to fail probably due to some API changes. Just a test issue I think.

**Comment by bdunlay** [comment]
Passing for all node versions now.

**Comment by tedeh** [comment]
Great stuff, thanks

**Comment by tedeh** [comment]
I want to add you to contributors in package.json. If you have an email or a web page you can reply with it here, or send a PR with the changes yourself.

**Pull request merged**
