### PR TITLE
Promise version Typescript fixes

### PR DESCRIPTION
**Pull request by mortiy**
Promise version should return only Promises

### CODE REVIEW

**Comment by BelfordZ** [comment]
LGTM plz

**Comment by BelfordZ** [comment]
wait, this doesnt work!

**Comment by karfau** [comment]
Just ran into this, would be great to land this to really allow typescript to properly use it with `async` `await`.
I mean it actually works but I need to shut up TSLINT, telling me that I'm awaiting something that is not a Promise.

**Comment by karfau** [comment]
With this rejected I'm happy I have moved away from this dependency

**Pull request closed without merging**
